name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
    TAG: 3.1.0

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build docker image
      run: docker build -t sabnzbd .
    - name: Tag images
      run:  |
          docker tag sabnzbd ${{ secrets.DOCKER_USERNAME }}/sabnzbd:${TAG}
          docker tag sabnzbd ${{ secrets.DOCKER_USERNAME }}/sabnzbd:latest
    - name: Push docker image
      run:  |
          docker push ${{ secrets.DOCKER_USERNAME }}/sabnzbd:${TAG}
          docker push ${{ secrets.DOCKER_USERNAME }}/sabnzbd:latest
