name: sabnzbd-pipeline

on:
  - push

env:
    TAG: 3.3.1

jobs:
  build:
    name: App and Container Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build docker image
      run: docker build -t sabnzbd .
       
    - name: Create tar for trivy
      run:  |
          docker save -o sabnzbd.tar sabnzbd

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        input: sabnzbd.tar
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: HIGH,CRITICAL

    - name: Tag docker images
      run:  |
          docker tag sabnzbd ${{ secrets.DOCKER_USERNAME }}/sabnzbd:${TAG}
          docker tag sabnzbd ${{ secrets.DOCKER_USERNAME }}/sabnzbd:latest
        
    - name: Push docker images
      run:  |
          docker push ${{ secrets.DOCKER_USERNAME }}/sabnzbd:${TAG}
          docker push ${{ secrets.DOCKER_USERNAME }}/sabnzbd:latest
