name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
    TAG: testing    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build docker image
      env:
        TAG: testing
      run: docker build --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/sabnzbd:${TAG} .
    - name: Push docker image
      run:  |
          docker push ${{ secrets.DOCKER_USERNAME }}/sabnzbd:${TAG}
